/**
 * Public types for the SDK judgment layer.
 *
 * A `JudgeBackend` answers bounded, typed questions about an explicit state.
 * It is the second injectable seam next to `LLMBackend`, and the SDK ships
 * specializations for an LLM, Jev (TypeSafe System One), and a mock.
 */

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

/** The three generic judgment kinds. */
export type JudgeQuestionKind = 'choose' | 'rate' | 'verify' | 'probability';

/**
 * How a value was produced. Kept explicit so uncalibrated numbers are never
 * mistaken for calibrated probabilities.
 */
export type JudgeBasis =
  | 'calibrated'
  | 'self_reported'
  | 'estimated'
  | 'label'
  | 'human'
  | 'mock';

export interface JudgeOption {
  id: string;
  description?: JsonValue | null;
}

export type JudgeLevel = JsonValue;

export interface JudgeQuestion {
  /** Stable id used in events and cache keys; generated by the bridge. */
  id: string;
  kind: JudgeQuestionKind;
  instruction: string | JsonValue;
  /** choose */
  options?: JudgeOption[];
  /** rate */
  levels?: JudgeLevel[];
  /** verify */
  criteria?: { true?: JsonValue | null; false?: JsonValue | null };
}

export interface JudgeAnswer {
  id: string;
  kind: JudgeQuestionKind;
  /** choose -> option id; rate -> level id; verify -> 'yes' | 'no' | 'unknown'. */
  value?: string;
  /** verify / probability. */
  probability?: number;
  /** choose / rate. */
  confidence?: number;
  /** Aligned to `options` or `levels`. */
  distribution?: number[];
  basis: JudgeBasis;
}

export interface JudgeCapabilities {
  calibrated: boolean;
  probability: boolean;
  confidence: boolean;
  independentQuestions: boolean;
  batch: boolean;
  structuredCriteria: boolean;
  maxQuestions: number;
  maxOptions: number;
  maxLevels: number;
  stateTokenBudget: number;
}

export interface JudgeUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens?: number;
}

export interface JudgeBackendRequest {
  state: JsonValue;
  questions: JudgeQuestion[];
  signal?: AbortSignal;
  model?: string;
  requiredCapabilities?: Array<keyof JudgeCapabilities>;
}

export interface JudgeBackendResponse {
  answers: JudgeAnswer[];
  model?: string;
  usage?: JudgeUsage;
}

export interface JudgeBackend {
  readonly id: string;
  readonly capabilities: JudgeCapabilities;
  complete(request: JudgeBackendRequest): Promise<JudgeBackendResponse>;
}

/**
 * Mutable selection shared between the SDK facade and the runner so a backend
 * can be registered or made default after construction.
 */
export interface JudgeSelection {
  backends: Map<string, JudgeBackend>;
  defaultName: string;
}

export const DEFAULT_JUDGE_CAPABILITIES: JudgeCapabilities = {
  calibrated: false,
  probability: false,
  confidence: false,
  independentQuestions: true,
  batch: true,
  structuredCriteria: false,
  maxQuestions: 128,
  maxOptions: 255,
  maxLevels: 10,
  stateTokenBudget: 32_000,
};

export function withJudgeCapabilities(
  overrides: Partial<JudgeCapabilities> | undefined,
): JudgeCapabilities {
  return { ...DEFAULT_JUDGE_CAPABILITIES, ...(overrides ?? {}) };
}
